project:
  type: website
  output-dir: docs

website:
  title: "hacking newb"
  navbar:
    right:
      - about.qmd
      - reference.qmd
      - icon: github
        href: https://github.com/
      - icon: mastodon
        href: https://infosec.exchange/@hacker_newb
format:
  html:
    theme: solar
    css: styles.css




